name: WFCCI

on:
  workflow_dispatch:

jobs:
  issue_copy:
    name: Copy issue to dest repository
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Transfer issue
        uses: dpanayotov/issue-cloner@v0.3
        with:
            label: "clone"
            targetRepo: mentorchita/GenerationTech
            token: ${{ secrets.SECRET_TOKEN }}        
          

