name: WFCCI

on:
  workflow_dispatch:

jobs:
  issue_copy:
    name: Copy issue to dest repository
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
              node-version: 16
      - name: Transfer issue
        uses: soichisumi/issue-copy-action@v0.2.0
        with:
            keyword: "/copy"
            targetRepository: mentorchita/GenerationTech
            githubToken: ${{ secrets.SECRET_TOKEN }}
            contentOfNewIssue: 'newly issue'
        
        
        
       
          

