name: WFCCI


on:
  issues:
  issue_comment:
  workflow_dispatch:
jobs:
  issue_copy:
    name: Copy issue to dest repository
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:  
    - name: Transfer Issue & Create Stub
      uses: lando/transfer-issue-action@v2
      with:
         token: ${{ secrets.SECRET_TOKEN }}
         router: newgen:GenerationTech


# on:
#  workflow_dispatch:

# jobs:
#  issue_copy:
#    name: Copy issue to dest repository
#    runs-on: ubuntu-latest
#    permissions:
#      issues: write
#    steps:
#      - name: Transfer issue
#        uses: caquino/issue-cloner@v0.10
#        with:
#           sourceLabel: "clone"
#           destinationLabel: "cloned"
#           targetRepo: mentorchita/GenerationTech
#           token: ${{ secrets.SECRET_TOKEN }}
